### ISSUE TITLE
SID zero

### ISSUE THREAD

**Issue by abierman** [core-wg/yang-cbor#101]
The SID draft should mention that SID value 0 is reserved and MUST NOT be assigned.
It is very common in code to use 0 for "not set" for handles and identifiers.

The sid typedef should not change. Just the directions to IANA.

**Comment by cabo** [comment]
0 to 999 are already marked as Reserved (Section 6 of RFC 8126).  I'm wondering how to mark 0 as even reserveder...

So this would be advice for (above Section 6):

            Reserved values can be released for assignment by the change
            controller for the registry (this is often the IESG, for
            registries created by RFCs in the IETF stream).

**Comment by cabo** [comment]
Maybe we should simply split this into 0 Reserved, never to be assigned, and 1-999 Reserved.

**Comment by mcr** [comment]
cabo ***@***.***> wrote:
    > 0 to 999 are already marked as Reserved (Section 6 of RFC 8126).  I'm
    > wondering how to mark 0 as even reserveder...

    > So this would be advice for (above Section 6):

    >             Reserved values can be released for assignment by the
    > change controller for the registry (this is often the IESG, for
    > registries created by RFCs in the IETF stream).

I'd move 1-999 to IETF Action, and mark 0 as allocated as invalid SID.
(Not reserved)

**Comment by cabo** [comment]
This is surprisingly hard to make a PR for.
The actual promise that 0 is not used for actual SIDs should be in YANG-CBOR (as that, at least in theory, can be used with a different SID allocation model).
I don't quite understand the RFC 8126 policies as allocated, e.g., where it says "RFC required", maybe "IETF review" was meant?  (What @mcr calls "IETF Action" is called "IETF review".  "Standards Action" would also be possible, but not needed here.)
