### ISSUE TITLE
sid: BK sid-file/module is optional.

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#104]
The yangdoctors review also asked why sid-file/module-name is optional,
which was tagged for follow-up.  I have the same question and am
interested in the outcome of the discussion amongst the authors.

**Comment by abierman** [comment]
Agreed. The "mandatory true" statement is needed for this leaf, but it does not solve all the issues.


- There is no official file-name. This is either out-of-scope or needs more work.
   - The module-name seems to be used as the file-name
- There may not be a module-name for SIDs in the Reserved space (see #96)
- The draft is silent about whether a "item" list entry MUST or SHOULD exist for namespace=module.
   - Even if it exists there could be submodule names in the this namespace so the module-name is not clear
-  The module-name is required to scope any "item" entries for the "identity" or "feature" namespace

**Comment by cabo** [comment]
Questions:

* What would a file-name be for?
* Do we need a sid-file for the netconf sids?  What would the identifiers be that this maps to?
* We completely ignore submodule names, so I'm not sure what the third item above is about
* Right, that should be documented.

**Comment by abierman** [comment]
Q1)
No need for a leaf with the file-name in it.
It is useful to name the SID file.
YANG files have standard naming conventions.
I think SID does as well so it is not a problem.

A server needs to convey to a client all the SID files in use on the server.
This is a protocol problem, not in scope here.

2) At some point this may be needed. Too early to tell yet

3) I need to review what is numbered in the "module" namespace.
Why would a SID file have a module-name to SID mapping for any other module
other than the one identified by module-name?
