### ISSUE TITLE
allocate SID value from IANA range for constrained-voucher

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#11]
Section 6.3.3
Please allocate a 50 SID range for draft-ietf-anima-constrained-voucher for the voucher-request, and a 50 SID range for the voucher (RFC8366) extension.
These could slide into 1400 and 1450 is you liked, or somewhere else, as you see fit.
Time is important here, as we have implementations that will need to change.

**Comment by lemikev** [comment]
Hi Michael

Range 1400 is already allocated to iana-hardware.
Please uses 2400 and 2450.
Send me your .yang files with or without your .sid files, I’ll register them in comi.space to avoid a conflicting allocations.

This is the list of the current registrations:
1000      100        30           ietf-comi
1100      50           1             ietf-yang-types
1150      50           1             ietf-inet-types
1200      50           4             iana-crypt-hash
1250      50           26           ietf-netconf-acm
1300      50           10           ietf-sid-file
1350      50           13           ietf-restconf
1400      100        16           iana-hardware
1500      100        62           ietf-interfaces
1600      100        63           ietf-ip
1700      100        75           ietf-system
1800      400        274        iana-if-type
2200      100        51           ietf-hardware
2300      50           9             ietf-datastores
2350      50           33           ietf-constrained-yang-library

Regards,
Michel

**Comment by cabo** [comment]
Is this an issue on yang-cbor?  Is this done?

**Comment by ivajloip** [comment]
Yes, with commit 05611792. The values from comi.space were used for the range and size entries in the sid draft.
