### ISSUE TITLE
ietf-sid-file: use sx:structure instead of rc:yang-data

### ISSUE THREAD

**Issue by abierman** [core-wg/yang-cbor#115]
I extracted the YANG module from the -latest editors version

    - changed import to use RFC 8791
    - removed rc:yang-data and replaced with sx:structure
    - moved sid-file grouping contents to a new grouping called sid-file-contents
    - other modules that import the grouping sid-file will continue to work as expected

[ietf-sid-file.yang.txt](https://github.com/core-wg/yang-cbor/files/7541192/ietf-sid-file.yang.txt)
[tree-latest.txt](https://github.com/core-wg/yang-cbor/files/7541196/tree-latest.txt)

tree generated with command

      pyang --tree-print-structures -f tree ietf-sid-file.yang

**Comment by cabo** [comment]
Thank you!

I'm not sure which version you used as input; there are a few things that look like an older version (e.g., http:// instead of https:// etc.).  I'll need to distill a minimum change version from that...

**Comment by abierman** [comment]
I used the link on the editors page
https://core-wg.github.io/yang-cbor/draft-ietf-core-yang-cbor-latest.txt

**Comment by abierman** [comment]
FAQ: How to convert rc:yang-data to sx:structure

https://yumaworks.freshdesk.com/a/solutions/articles/1000307178
