### ISSUE TITLE
YANG features resolution

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#124]
> 4. How does the CBOR encoding of SIDs apply to YANG features?  This draft
> references features and the SID draft allows SIDs for them, but I don't
> understand how they are used in the encoding (since features don't appear in
> the instance data, they are only at the schema level).

YANG features only show up on the value side.

**Comment by cabo** [comment]
Proposed response text:

YANG features can occur in the data of a YANG module, e.g., yang-library (RFC 8525).  Using a SID instead of an identifier for a feature allows a compact representation.
