### ISSUE TITLE
remove single reference to "child" from yang-cbor

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#125]
> Where this causes problems are in the definitions of: 'child' - (e.g., 'case'
> cannot be a child of a 'container' only a child of a 'choice', and equivalently
> for the definition of 'parent'.  This definitions are not heavily used and
> could perhaps be removed?

Check if it used in core-sid.

**Comment by cabo** [comment]
Either is not used in core-sid.  Parent is used seven times, so I left it in.
