### ISSUE TITLE
Remove "case" from "parent" definition

### ISSUE THREAD

**Issue by cabo** [core-wg/yang-cbor#134]
Parent needs to be defined as he "closest enclosing" (or it becomes ancestor).

From the kinds of schema nodes listed (container, list, case, notification, RPC input, RPC output, action input or action output node), one stands out:
A "case" statement is not an interesting parent, is it?
We don't represent it in the data tree.

**Comment by mcr** [comment]
We need to remove "case" from this situation.

**Comment by mcr** [comment]
Just say, "The parent node in the data tree"

**Comment by cabo** [comment]
This is now addressed in #136 using the term "representation node".
