### ISSUE TITLE
comments from Rob Wilton: SIDs and submodules

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#27]
~~~~
(2) I think that this document should be clearer as to the relationship between 
SIDs and submodules (more details in the comment).
~~~~

1. Regarding the relationship between sids and submodules, I think is best summed up by this comment in the appendix: "Note that ".sid" files can only be generated for YANG modules and not for submodules."  I.e., I don't think that sids should be allocated for the name of the submodule, and any items within a submodule are effectively allocated sids as part of processing the module that includes them.  This topic should be addressed early in the document, and probably the existing references to submodule in the introduction and the YANG module can be removed.

**Comment by abierman** [comment]
I agree with Rob.
The CORECONF YANG Library uses this SID type I think.
SIDs for module/submodule/feature are not critical since reading the library is done infrequently.
YANG module and submodule names share the same namespace BTW
