### ISSUE TITLE
Éric Vyncke: YANG schema vs YANG module

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#34]
I will let my OPS and Management AD to comment on the use of 'YANG schema' rather than 'YANG module' and about the word 'item' for many YANG-related concepts.

**Comment by cabo** [comment]
As of today, we only have "yang schema" in combinations such as "yang schema identifier (YANG SID)".  
"item" is occasionally used in RFC 7950, but not formally defined there, so we supply our own definition.

**Comment by mcr** [comment]
> Arguably, the RFC 7950
> definition of a data node is somewhat confusing. - please check everywhere
> where 'schema node' or 'data node' turns up in the text to ensure that you are
> referencing instances of that schema node rather than the schema node itself. 
> E.g., the second paragraph in section 3 states 'where each child schema node
> is encoded ...', but this should be an instance of child schema node. - ensure
> that if you are referring to the parent or child of a 'schema node' that the
> logic skip out the schema nodes that don't get encoded in the data tree. 
> E.g., when calculating SIDs.

TO DO.

**Comment by cabo** [comment]
Addressed by #136 now.
