### ISSUE TITLE
yang-cbor: BK valid a way to represent the given YANG element

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#43]
(4) Relatedly, the second example of instance-identifier by name (§6.13.2)
does not show a country for "authorized-key", and I'm not sure if that's
a valid way to represent the given YANG element.

**Comment by cabo** [comment]
I'm confused, the keys of `authorized-key` are `name` and not `country`.

**Comment by mcr** [comment]
@abierman will look for a nested lists in a table with two keys.
We should leave 7317 example (unchanged) in the document.
@ivajloip will revert 7317 example and fix it.

**Comment by mcr** [comment]
@cabo will also look at how the JSON encoding works, compared to Xpath.

**Comment by cabo** [comment]
Ugh, RFC 7951 simply uses the XPath syntax.  We could unwrap that similar to the way the SID version works, with an array of names leading down the tree instead of a single SID.

**Comment by abierman** [comment]
The AD comment about the incorrect example has been fixed.
I think sec. 4.4.1 has an example for a list that shows how to encode the delta SIDs.
Suggest saving #79 for a future draft focusing on YANG Push

**Comment by cabo** [comment]
This is indeed addressed now (9cdbc17).
