### ISSUE TITLE
yang-cbor, BK comments part 1

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#44]
I can see why it would not make sense to do so in this document that is
so tightly integrated with CORECONF, but is there any work to produce a
CBOR encoding for the "structure" extension from RFC 8791?

As a general note, I did not look particularly carefully at the example
CBOR encodings, on the assumption that they were automatically generated
as part of the document production process.

Section 4.2

   This specification supports two types of CBOR keys; SID as defined in
   Section 3.2 and names as defined in Section 3.3.

I suggest making an explicit statement about whether the two types of
keys can be comingled in the same container/etc, possibly just by
forward-reference to the media-type parameter.

Section 4.2.1

   In the context of containers and other nodes from the data tree, CBOR
   map keys within inner CBOR maps can be encoded using deltas or SIDs.
   In the case of deltas, they MUST be encoded using a CBOR unsigned
   integer (major type 0) or CBOR negative integer (major type 1),
   depending on the actual delta value.  [...]

It's a little surprising that we only get this extended discussion on
SID use in §4.2.1, when we already had §4.1.1 "Using SIDs in keys" that
said almost nothing about it.

Section 4.2.2

   [...] A namespace-qualified name
   MUST be used each time the namespace of a schema node and its parent
   differ.  In all other cases, the simple form of the name MUST be
   used.  [...]

We have a similar statement in §3.3 that is only "the simple form of the
name SHOULD be used" for the latter sentence.  It's not entirely clear
to me what causes the strength of requirement to be different between
the two cases.

Section 4.6

Do we want to explicitly acknowledge the mismatch between the "xml" in
"anyxml" and the actual CBOR contents?

**Comment by mcr** [comment]
> I can see why it would not make sense to do so in this document that is so tightly integrated with CORECONF, but is there any work to produce a CBOR encoding for the "structure" extension from RFC 8791?

To be covered in #48

**Comment by mcr** [comment]
````
Do we want to explicitly acknowledge the mismatch between the "xml" in
"anyxml" and the actual CBOR contents?
````

Only XML elements are supported, and other things are to be skipped.  Need to update section 4.6 to more explicitely say this.

**Comment by cabo** [comment]
We should copy whatever RFC7951 says about this.

**Comment by lemikev** [comment]
I don't understand why Michael say "Only XML elements are supported, and other things are to be skipped."
- In https://datatracker.ietf.org/doc/html/rfc7950#section-7.11, anyxml "represent an unknown chunk of XML"
- In https://datatracker.ietf.org/doc/html/rfc7951#section-5.6, anyxml "is encoded as a JSON name/value pair".
- In https://datatracker.ietf.org/doc/html/draft-ietf-core-yang-cbor#section-4.6, anyxml "is used to serialize an arbitrary CBOR content"

I thinks the comment was about the fact that anyxml do not carry xml data in the case of JSON and CBOR.

**Comment by abierman** [comment]
The anyxml construct allows mixed mode XML (e.g. sloppy HTML).
This is not allowed in anydata.
anyxml also allows processing instructions and comments, and anydata does not.

Unless there is a way to encode all these things in CBOR then better to say
that only the XML elements present in anyxml data are encoded in CBOR

**Comment by cabo** [comment]
This is now overtaken by draft -19, which addresses all ADs' comments.

**Comment by cabo** [comment]
Response mail Archived-At: <https://mailarchive.ietf.org/arch/msg/core/PNVNWUGZ3ZbSdujKexhUwkCyLkY>
