### ISSUE TITLE
yang-cbor RW terminology comments

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#47]
1. The document should be clearer on its use of terminology around schema nodes.  Mostly the encoding related to YANG data nodes, not YANG schema nodes.  I've provided more information in the comments section.

2. I find this document (along with the SID draft), somewhat confusing in that it references YANG schema nodes, but in most cases, it probably
only cares about the subset of YAND schema nodes that represent itemsthat are present in data tree instantiation.  RFC 7950 calls such 'schema nodes' as 'data nodes'.  For example, 'choice', 'case', 'input' and 'output' exist as nodes in the YANG schema tree, but are not data nodes and don't appear as instantiated data nodes.

Where this causes problems are in the definitions of: 'child' - (e.g., 'case' cannot be a child of a 'container' only a child of a 'choice', and equivalently for the definition of 'parent'.  This definitions are not heavily used and could perhaps be removed?

Hence my suggestion to clarify the text are:
 - potentially import and use data node rather than schema node.  Note that data node, as defined in RFC 7950, is a subset of schema nodes, so you still need the text saying an instance of a data node.  Arguably, the RFC 7950 definition of a data node is somewhat confusing.
 - please check everywhere where 'schema node' or 'data node' turns up in the text to ensure that you are referencing instances of that schema node rather than the schema node itself.  E.g., the second paragraph in section 3 states 'where each child schema node is encoded ...', but this should be an instance of child schema node.
 - ensure that if you are referring to the parent or child of a 'schema node' that the logic skip out the schema nodes that don't get encoded in the data tree.  E.g., when calculating SIDs.

**Comment by mcr** [comment]
We need to just say, somewhere, that not all schema nodes are numbered with SIDs.

**Comment by abierman** [comment]
I agree with Rob about this comment

pt 1&2) A SID identifies a YANG schema node that corresponds to a data node. This excludes the 'choice', 'case', 'input' and 'output' schema nodes.

part 2: SIDs are used to represent data node identifiers and (in some cases) data node content,
within protocol-specific messages or artifacts.

**Comment by cabo** [comment]
Resolved (in a different way) in #136 now.
