### ISSUE TITLE
cbor-yang RW Query about YANG features

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#49]
4. How does the CBOR encoding of SIDs apply to YANG features?  This draft references features and the SID draft allows SIDs for them, but I don't understand how they are used in the encoding (since features don't appear in the instance data, they are only at the schema level).

**Comment by abierman** [comment]
features are metadata.
they have no coding ever in YANG data, just listed in the YANG Library for the server.

This is another special SID for the CoMI YANG Library.

**Comment by cabo** [comment]
Proposed reply:

YANG features can occur in the data of a YANG module, e.g., yang-library (RFC 8525).  Using a SID instead of an identifier for a feature allows a compact representation.
