### ISSUE TITLE
yang-cbor RW editorial comments

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#51]
3. I think that some of the references to submodules are not quite right.  Basically, the CBOR encoding should not need to concern itself about submodules at all, since logically, it works with the module schema (which logically incorporates the submodules).  E.g., perhaps you could mention this in the introduction, referencing section 4.2.1 (4th paragraph in particular) of RFC 7950?

Hence:
In section 2:
   *  item: A schema node, an identity, a module, a submodule, or a
      feature defined using the YANG modeling language.

I think that this should exclude submodule (and possibly feature as well).

In section 3.2:
   YANG modules, submodules, and features

I don't think that you want submodules in this list (and perhaps not features either).

And in: 
	6.13.1.  SIDs as instance-identifier

	   SIDs uniquely identify a schema node.  In the case of a single
	   instance schema node, i.e., a schema node defined at the root of a
	   YANG module or submodule or schema nodes defined within a container,
	   the SID is sufficient to identify this instance.

I would remove "or submodule" from this text.  Effectively, the text about
modules already covers this.

4. Please check the text that describes how lists are encoded.  Section 4.2 seems to suggest that they are encoded as a CBOR Map, section 4.4 states that they are encoded as an array.  I presume that the answer is that they encode the list is an array, and each list entry is a Map.

5.
   Values of 'bits' types defined in a 'union' type MUST be encoded
   using a CBOR text string data item (major type 3) and MUST contain a
   space-separated sequence of names of 'bits' that are set
   
It might be helpful to have a quick sentence to justify why this is done.

**Comment by cabo** [comment]
RW-3 closed by #83 
Rest to be closed by #86
