### ISSUE TITLE
Is the name "SID" overloaded?

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#78]
There are long threads in 6man about SID, as related to SRH/Spring/etc.
I wonder if we might want to change our TLA.

**Comment by cabo** [comment]
It was SID for the first few years.  Then segment routing used SID, and so we use YANG SID wherever that helps (SID now is just short form where it is unambiguous).

SNID is a nice idea, but has weird connotations to me (snide, snag, sneer, snob, snub...).

I would be more open to inventing/switching to a new acronym if the existing one weren't already ingrained in the file formats.

**Comment by abierman** [comment]
No -- this battle was already fought and the current YANG Schema Item IDentifier (also called SID)
is good enough. The official name should be used more often to remind people it is YANG SID.
